import Header from '@/components/Header';

export default function FAQRSV() {
  return (
    <div className="min-h-screen">
      <Header />
      
      {/* Hero Section */}
      <main className="hero">
        <h1 className="hero-title animate-fade-in-up">
          Vaccine
          <br />
          Talk
          </h1>
        
        <p className="hero-subtitle animate-fade-in-up animate-delay-1">
          (Egyptian Edition)
        </p>
        
        <div className="hero-quote animate-fade-in-up animate-delay-2">
          <p>"Everything you need to know about</p>
          <p>vaccines in Egypt"</p>
        </div>
      </main>
      
      {/* Simple centered title */}
      <section style={{padding:'0.5rem 1rem 0'}}>
        <h2 className="about-lang-title" style={{textAlign:'center', fontSize:'2rem', margin:'0'}}>FAQ – RSV</h2>
      </section>

      {/* RSV FAQ content */}
      <section className="about-section">
        <div className="about-elegant-card">
          <div className="card-corner card-corner-tl"></div>
          <div className="card-corner card-corner-tr"></div>
          <div className="card-corner card-corner-bl"></div>
          <div className="card-corner card-corner-br"></div>
          <div className="about-bilingual">
            <div className="about-lang" style={{alignItems:'flex-start'}}>
              <h3 style={{textAlign:'left', fontSize:'1.15rem', fontWeight:700, color:'#40606D', direction: 'ltr'}}>What is respiratory syncytial virus (RSV)?</h3>
              <p className="about-lang-intro" style={{direction: 'ltr', textAlign: 'left'}}>Respiratory syncytial virus (RSV) is a common respiratory virus, usually causing mild, cold-like symptoms, such as cough, runny nose, sore throat, headache, fatigue, and fever. Though most people recover in a few days, for some people, RSV can cause serious lower respiratory tract infection (LRTI), such as bronchiolitis or pneumonia. RSV is the most common cause of hospitalization in infants in the United States. Older adults, especially those with chronic health conditions and those age 75 and older, are also more likely to develop severe RSV disease and need hospitalization. There is no specific treatment for RSV illness, only supportive care.</p>
              <p className="about-lang-intro" style={{direction: 'ltr', textAlign: 'left'}}>RSV causes annual outbreaks of respiratory illness in people of all ages. In the continental United States, RSV typically circulates in the fall and winter months, between October and March, although its seasonality can vary locally from year to year.</p>

              <h3 style={{textAlign:'left', fontSize:'1.15rem', fontWeight:700, color:'#40606D', direction: 'ltr'}}>Among adults, who is most at risk for serious RSV infection?</h3>
              <p className="about-lang-intro" style={{direction: 'ltr', textAlign: 'left'}}>Most adults experience a mild upper respiratory tract infection with RSV, with symptoms lasting only a few days. Some adults with RSV develop lower respiratory tract disease, including pneumonia. The risk for severe RSV infection increases substantially with increasing age, especially among those who are 75 years of age and older. Risk is also increased for those who have one or more chronic health conditions, including people who are moderately or severely immunocompromised and people who are considered frail or who live in a nursing home or long-term care facility. Among those with health conditions, the risk of hospitalization goes up significantly with age and among those who have multiple health conditions.</p>

              <h3 style={{textAlign:'left', fontSize:'1.15rem', fontWeight:700, color:'#40606D', direction: 'ltr'}}>How serious is RSV in children?</h3>
              <p className="about-lang-intro" style={{direction: 'ltr', textAlign: 'left'}}>Almost all U.S. infants and toddlers contract RSV illness within the first two years of life. RSV causes a mild respiratory illness in most, with symptoms including cough, runny nose, fever, and fatigue. Illness is more likely to be mild if the child is older at the time of first infection. Infants with RSV infection frequently develop bronchiolitis, a lower respiratory tract disease (LRTD) that can be severe.</p>

              <h3 style={{textAlign:'left', fontSize:'1.15rem', fontWeight:700, color:'#40606D', direction: 'ltr'}}>Does RSV have a typical season?</h3>
              <p className="about-lang-intro" style={{direction: 'ltr', textAlign: 'left'}}>In most temperate regions of the continental United States and other areas with similar climates, RSV season typically begins in the fall and peaks in the winter, generally circulating between October and the end of March. However, the timing and severity of RSV season in a given community can vary from year to year.</p>

              <h3 style={{textAlign:'left', fontSize:'1.15rem', fontWeight:700, color:'#40606D', direction: 'ltr'}}>What are the three RSV vaccines and how are they different?</h3>
              <p className="about-lang-intro" style={{direction: 'ltr', textAlign: 'left'}}>There are three RSV vaccines licensed and recommended in the United States. Each is listed below, along with their FDA-licensed indications:</p>
              <p className="about-lang-intro" style={{direction: 'ltr', textAlign: 'left'}}><strong>Abrysvo (RSVpreF, Pfizer, originally licensed May 2023):</strong> For all adults age 60 years or older, adults age 18 through 59 years with high-risk conditions for severe RSV disease, and during pregnancy from 32 through 36 weeks' gestation</p>
              <p className="about-lang-intro" style={{direction: 'ltr', textAlign: 'left'}}><strong>Arexvy (RSVpreF3, GSK, originally licensed May 2023):</strong> For all adults age 60 years or older, adults age 50 through 59 years with high-risk conditions for severe RSV disease</p>
              <p className="about-lang-intro" style={{direction: 'ltr', textAlign: 'left'}}><strong>mResvia (mRNA RSV, Moderna, originally licensed May 2024):</strong> For all adults age 60 years or older, adults age 18 through 59 years with high-risk conditions for severe RSV disease</p>
              <p className="about-lang-intro" style={{direction: 'ltr', textAlign: 'left'}}>All three may be used as recommended by CDC and ACIP as a single dose for all adults age 75 years or older and for adults age 50 through 74 years with high-risk conditions for severe RSV disease. Only Abrysvo is licensed for use during pregnancy (during 32 through 36 weeks and 6 days' gestation) for the prevention of RSV disease in infants.<br />
              Arexvy and Abrysvo are recombinant protein vaccines that contain the prefusion form of the F protein found on the surface of the RSV virus. The mResvia mRNA vaccine contains mRNA that encodes the prefusion form of the RSV F glycoprotein. The mRNA vaccine temporarily enables some of the vaccine recipient's own cells to produce the prefusion form of the RSV F protein, causing the immune system to respond by generating antibodies to it. Because none of these vaccines contain live virus, they cannot cause RSV illness.<br />
              The GSK vaccine, Arexvy, includes an AS01adjuvant, a chemical designed to enhance the immune response to vaccination. AS01 is the same adjuvant used in GSK's recombinant zoster vaccine (Shingrix), but Arexvy contains half the amount of adjuvant as a dose of Shingrix. Abrysvo and mResvia vaccines do not contain an adjuvant.</p>

              <h3 style={{textAlign:'left', fontSize:'1.15rem', fontWeight:700, color:'#40606D', direction: 'ltr'}}>How well do the RSV vaccines work for older adults?</h3>
              <p className="about-lang-intro" style={{direction: 'ltr', textAlign: 'left'}}>All three RSV vaccines were effective in preventing RSV-associated lower respiratory tract disease (LRTD) in clinical trial participants, over the course of two RSV seasons.<br />
              The global clinical trials for RSVPreF3 (Arexvy, GSK) vaccine involved nearly 25,000 participants and some participants were followed for 2 RSV seasons. One dose reduced the risk of laboratory-confirmed RSV-associated LRTD with two or more symptoms by 82.6% during the first RSV season and 56.1% during the second season. In studies of the real-world effectiveness of Arexvy during the 2023–2024 RSV season, the first since licensure of Arexvy, Arexvy was approximately 77% effective in preventing RSV-associated emergency department encounters and 83% effective in preventing RSV-associated hospitalizations in adults 60 and older.<br />
              The RSVpreF (Abrysvo, Pfizer) vaccine global clinical trials involved nearly 37,000 participants, and some participants were followed for 2 RSV seasons. One dose reduced the risk of symptomatic, laboratory-confirmed RSV-associated LRTD with 3 or more symptoms by 88.9% during the first RSV season and 78.6% during a partial second season. In studies of the real-world effectiveness of Abrysvo during the 2023–2024 RSV season, the first RSV season since licensure, Abrysvo was approximately 79% effective in preventing RSV-associated emergency department encounters and 73% effective in preventing RSV-associated hospitalizations in adults 60 and older.<br />
              The mRNA RSV (mResvia, Moderna) vaccine global clinical trials involved nearly 37,000 participants. One dose reduced the risk of symptomatic laboratory-confirmed RSV LRTD with three or more symptoms by 80.9% in the first season. After a median follow up time of 18.8 months, its efficacy declined to 48.4%. Because mResvia was licensed so recently, real-world vaccine effectiveness against RSV-associated hospitalization and other severe illness cannot yet be estimated.<br />
              Few people enrolled in the clinical trials were either frail or of advanced age (80 or older), and none lived in long-term care facilities. People with immunocompromising conditions were excluded from clinical trials. For this reason, the clinical trials did not measure how well the vaccines would work in the people at highest risk of serious RSV disease. However, CDC notes that real-world data for Arexvy and Abrysvo during the 2023–2024 RSV season demonstrated effectiveness in these groups.</p>

              <h3 style={{textAlign:'left', fontSize:'1.15rem', fontWeight:700, color:'#40606D', direction: 'ltr'}}>Is there information on how well RSV vaccines have worked in the first season they were used?</h3>
              <p className="about-lang-intro" style={{direction: 'ltr', textAlign: 'left'}}>Yes.<br />
              In studies of the real-world effectiveness of Arexvy during the 2023–24 RSV season, the first since licensure of Arexvy, Arexvy was approximately 77% effective in preventing RSV-associated emergency department encounters and 83% effective in preventing RSV-associated hospitalizations in adults age 60 and older.<br />
              In studies of the real-world effectiveness of Abrysvo during the 2023–24 RSV season, the first RSV season since licensure, Abrysvo was approximately 79% effective in preventing RSV-associated emergency department encounters and 73% effective in preventing RSV-associated hospitalizations in adults age 60 and older.<br />
              The Moderna mResvia vaccine was first used during the 2024–25 season. Real-world effectiveness data are not yet available.</p>

              <h3 style={{textAlign:'left', fontSize:'1.15rem', fontWeight:700, color:'#40606D', direction: 'ltr'}}>How long will protection from RSV vaccine last?</h3>
              <p className="about-lang-intro" style={{direction: 'ltr', textAlign: 'left'}}>Currently, protection from serious lower respiratory tract disease (LRTD) after RSV vaccination is expected to last for at least two RSV seasons, but exactly how well it protects over a longer period of time is not yet known. In clinical trials, the ability of the vaccine to reduce the risk of serious lower respiratory tract disease was tested in some people over 2 RSV seasons, and all RSV vaccines provided meaningful protection in the second season.<br />
              RSV vaccination is currently recommended as a single dose: revaccination is not yet recommended. ACIP will update its recommendations concerning whether to revaccinate, and when, as more data become available over time concerning how long protection from a single dose lasts and how effective revaccination is in boosting protection. A small study by GSK did not show a meaningful benefit of revaccination with Arexvy just one year after dose 1; however, revaccinating after a longer interval might be helpful. Studies are underway to evaluate the benefit of revaccination at different intervals.</p>

              <h3 style={{textAlign:'left', fontSize:'1.15rem', fontWeight:700, color:'#40606D', direction: 'ltr'}}>How often should the RSV vaccine be given?</h3>
              <p className="about-lang-intro" style={{direction: 'ltr', textAlign: 'left'}}>All three RSV vaccines are currently licensed and recommended as a one-time dose for any person. Recommendations for revaccination have not been made. At this time, a pregnant person who receives Abrysvo (Pfizer) during one pregnancy is not recommended to receive Abrysvo during a subsequent pregnancy: in subsequent pregnancies, the baby should receive an RSV preventive antibody after delivery for RSV protection. ACIP will make decisions concerning RSV revaccination as more data become available over time.</p>

              <h3 style={{textAlign:'left', fontSize:'1.15rem', fontWeight:700, color:'#40606D', direction: 'ltr'}}>Can any of the three licensed RSV vaccines be used during pregnancy?</h3>
              <p className="about-lang-intro" style={{direction: 'ltr', textAlign: 'left'}}>Only the RSVpreF vaccine, Abrysvo by Pfizer, is licensed and recommended for one-time use between 32 weeks and 36 weeks 6 days of gestation to prevent RSV-associated lower respiratory tract disease in infants younger than 6 months old. Do not use Arexvy (GSK) or mResvia (Moderna) during pregnancy. If a pregnant person received an RSV vaccine before the current pregnancy, do not use Abrysvo during this pregnancy. Instead, counsel them that a dose of RSV preventive antibody will be needed to protect the infant from RSV after birth.</p>

              <h3 style={{textAlign:'left', fontSize:'1.15rem', fontWeight:700, color:'#40606D', direction: 'ltr'}}>What is the ACIP recommendation for RSV vaccination of older adults?</h3>
              <p className="about-lang-intro" style={{direction: 'ltr', textAlign: 'left'}}>ACIP routinely recommends a single dose of any of the three licensed RSV vaccines for all adults age 75 years and older. ACIP also recommends a single dose of any RSV vaccine for adults age 50 through 74 years who are increased risk for serious RSV infection due to specific high-risk conditions, frailty, or high-risk living arrangements (e.g., residents of long-term care facilities).</p>
              <p className="about-lang-intro" style={{direction: 'ltr', textAlign: 'left'}}>In April 2025, ACIP voted to lower the age for initiating vaccination of high-risk adults from age 60 years to age 50 years. The recommendation was accepted and made official in the summer of 2025. The indications for those age 50 through 59 years are the same as those published for people age 60 through 74 years.</p>

              <h3 style={{textAlign:'left', fontSize:'1.15rem', fontWeight:700, color:'#40606D', direction: 'ltr'}}>What are the high-risk conditions specified by ACIP as indications for RSV vaccination among adults age 50 through 74 years?</h3>
              <p className="about-lang-intro" style={{direction: 'ltr', textAlign: 'left'}}>Because of the strong association between the risk of severe RSV disease and age, ACIP recommends RSV vaccination of all adults age 75 years or older. ACIP has specified several conditions as reasons for RSV vaccination before age 75 years (age 50 through 74 years) due to their association with a high risk of hospitalization with severe RSV disease compared to otherwise healthy adults of the same age. ACIP voted to lower the youngest age for vaccination of adults at high risk from 60 years to 50 years in April 2025, but the risk groups are unchanged. These conditions are similar to, but not the same as, high-risk conditions specified for pneumococcal or influenza vaccination. An individual's risk is increased further if they have more than one of the conditions.<br />
              <strong>Non-immunocompromising chronic health conditions:</strong><br />
              Chronic cardiovascular disease (such as heart failure, coronary artery disease, or congenital heart disease [excluding isolated hypertension])<br />
              Chronic lung disease (such as chronic obstructive lung disease [COPD], emphysema, asthma, interstitial lung disease, or cystic fibrosis)<br />
              End-stage kidney disease or dependence on hemodialysis or other renal replacement therapy<br />
              Diabetes mellitus complicated by chronic kidney disease, neuropathy, retinopathy, or other end-organ damage, or requiring treatment with insulin or sodium-glucose cotransporter-2 (SGLT2) inhibitor<br />
              Severe obesity (measured as a body mass index of 40 kilograms per meter squared or greater)<br />
              Chronic liver disease (such as cirrhosis)<br />
              Neurologic or neuromuscular conditions causing impaired airway clearance or respiratory muscle weakness (such as poststroke dysphagia [swallowing dysfunction], amyotrophic lateral sclerosis [ALS], or muscular dystrophy [excluding history of stroke without impaired airway clearance])<br />
              Chronic blood disorders (such as sickle cell disease, thalassemia)<br />
              <strong>Moderate or severe immune compromise</strong> (due to a medical condition or due to immunosuppressive medications or treatment)<br />
              <strong>Overall frailty</strong> (based on an assessment of frailty)<br />
              <strong>Residence in a nursing home or other long-term care facility</strong><br />
              Other chronic medical conditions or risk factors not specified in this list that a healthcare provider determines might increase the risk of severe disease due to RSV respiratory infection<br />
              People age 50 through 74 years who do not have a medical condition or risk factor that increases their risk of severe RSV disease are not recommended to receive RSV vaccine: they should wait to be vaccinated until a high-risk condition develops or until they turn 75, whichever comes first.</p>

              <h3 style={{textAlign:'left', fontSize:'1.15rem', fontWeight:700, color:'#40606D', direction: 'ltr'}}>What kind of immunocompromising conditions count as risk factors that justify vaccination against RSV between age 50 and 74 years?</h3>
              <p className="about-lang-intro" style={{direction: 'ltr', textAlign: 'left'}}>CDC specifies for RSV vaccination the same moderate to severe immunocompromising conditions that require additional doses of COVID-19 vaccines.<br />
              Moderate and severe immunocompromising conditions and treatments include but are not limited to:<br />
              Active treatment for solid tumor and hematologic malignancies<br />
              Hematologic malignancies associated with poor responses to COVID-19 vaccines regardless of current treatment status (e.g., chronic lymphocytic leukemia, non-Hodgkin lymphoma, multiple myeloma, acute leukemia)<br />
              Receipt of solid-organ transplant or an islet transplant and taking immunosuppressive therapy<br />
              Receipt of chimeric antigen receptor (CAR)-T-cell therapy or hematopoietic cell transplant (HCT) (within 2 years of transplantation or taking immunosuppressive therapy)<br />
              Moderate or severe primary immunodeficiency (such as common variable immunodeficiency disease, severe combined immunodeficiency, DiGeorge syndrome, or Wiskott-Aldrich syndrome)<br />
              Advanced HIV infection (people with HIV and CD4 cell counts less than 200 per cubic milliliter, history of an AIDS-defining illness without immune reconstitution, or clinical manifestations of symptomatic HIV) or untreated HIV infection<br />
              Active treatment with high-dose corticosteroids (i.e., 20 mg or more of prednisone or equivalent per day when administered for 2 or more weeks), alkylating agents, antimetabolites, transplant-related immunosuppressive drugs, cancer chemotherapeutic agents classified as severely immunosuppressive, tumor necrosis factor (TNF) blockers, and other biologic agents that are immunosuppressive or immunomodulatory (e.g., B-cell-depleting agents)<br />
              Factors to consider in assessing the general level of immune competence in a patient include disease severity, duration, clinical stability, complications, comorbidities, and any potentially immune-suppressing treatment.</p>

              <h3 style={{textAlign:'left', fontSize:'1.15rem', fontWeight:700, color:'#40606D', direction: 'ltr'}}>I have a 69-year-old patient who requested RSV vaccination. He has controlled hypertension and no other underlying medical conditions. Is RSV vaccination indicated?</h3>
              <p className="about-lang-intro" style={{direction: 'ltr', textAlign: 'left'}}>No. RSV vaccination is not recommended for people his age with hypertension and no other risk conditions. People age 50 through 74 years who do not have a medical condition or risk factor that increases their risk of severe RSV disease are not recommended to receive RSV vaccination at this time.</p>

              <h3 style={{textAlign:'left', fontSize:'1.15rem', fontWeight:700, color:'#40606D', direction: 'ltr'}}>Why did ACIP change its RSV vaccination recommendations for older adults in 2024 to remove the option for vaccination of healthy people 60 through 74 who would like to be vaccinated?</h3>
              <p className="about-lang-intro" style={{direction: 'ltr', textAlign: 'left'}}>In 2023, when RSV vaccines were initially licensed, ACIP recommended use of RSV vaccine for anyone 60 years and older based on shared clinical decision-making, which includes a conversation about individual risks and benefits of vaccination with a healthcare provider. The recommendation was made when there were limited data about how well the vaccine would work in preventing RSV-associated hospitalization or death due to the relatively healthy older adults enrolled in the clinical trials. There was also a question about whether (or how frequently) a person would need revaccination and whether the vaccination might increase the rare risk of Guillain-Barré syndrome. Given these uncertainties, ACIP members felt that people should have the option to choose to receive RSV vaccine or wait until their risk of serious RSV disease escalates, as it does after age 75. Shared clinical decision-making proved time-consuming and difficult to implement for healthcare providers and patients, due to the lack of clarity about who should prioritize RSV vaccination.<br />
              Updated evidence on the balance of RSV vaccination benefits and risks led ACIP in June 2024 to make a definitive routine age-based recommendation for adults age 75 years and older, accompanied by a risk-based recommendation for those age 60 through 74 years with specific high-risk conditions. Due to the relatively small benefit of vaccination for healthy people younger than age 75 and the ongoing uncertainty about revaccination, the option for vaccination of people age 60 through 74 years without risk factors for severe RSV disease was removed. In April 2025, ACIP voted to lower the age to initiate vaccination of adults at high risk of serious RSV disease from 60 years to 50 years.</p>

              <h3 style={{textAlign:'left', fontSize:'1.15rem', fontWeight:700, color:'#40606D', direction: 'ltr'}}>In 2023, my 62-year-old patient and I agreed that he would defer RSV vaccination because he was in good health and at low risk of serious RSV. He remains healthy and is asking about RSV vaccination now, but he's not 75. What should I do?</h3>
              <p className="about-lang-intro" style={{direction: 'ltr', textAlign: 'left'}}>As long as he remains healthy, let him know that he can wait until age 75 to get an RSV vaccine. Plan to reassess his need for RSV vaccination periodically. If he develops a high-risk condition that puts him at increased risk of severe RSV disease before turning 75, you should vaccinate him at that point.</p>

              <h3 style={{textAlign:'left', fontSize:'1.15rem', fontWeight:700, color:'#40606D', direction: 'ltr'}}>Is RSV vaccine an annual vaccination, like influenza?</h3>
              <p className="about-lang-intro" style={{direction: 'ltr', textAlign: 'left'}}>No. Only a single dose of RSV vaccine is currently approved and recommended. There is no evidence at this time to determine if or when revaccination would be of value. Available evidence from clinical trials indicates that RSV vaccination provides meaningful protection against severe RSV disease for at least 2 RSV seasons.</p>
              <p className="about-lang-intro" style={{direction: 'ltr', textAlign: 'left'}}>People who were vaccinated for RSV during a previous pregnancy and are pregnant again should not receive RSV vaccination for prevention of RSV in their infant. Instead, the infant should be immunized with an RSV preventive antibody after delivery for RSV protection.</p>

              <h3 style={{textAlign:'left', fontSize:'1.15rem', fontWeight:700, color:'#40606D', direction: 'ltr'}}>May influenza vaccines be given at the same time as RSV vaccine?</h3>
              <p className="about-lang-intro" style={{direction: 'ltr', textAlign: 'left'}}>Yes, coadministration of influenza and RSV vaccines at the same visit is acceptable.</p>

              <h3 style={{textAlign:'left', fontSize:'1.15rem', fontWeight:700, color:'#40606D', direction: 'ltr'}}>What is the recommendation for use of RSV vaccine during pregnancy?</h3>
              <p className="about-lang-intro" style={{direction: 'ltr', textAlign: 'left'}}>Pregnant patients between 32 and 36 weeks and 6 days' gestation during the months of September through January in the United States should get one dose of the Pfizer RSVpreF vaccine (Abrysvo) to protect their babies during their first RSV season after birth. Only Abrysvo is FDA-approved and recommended for pregnant patients. Arexvy (by GSK) and mResvia (Moderna) are not approved and should not be given during pregnancy.<br />
              In most of the continental United States, maternal RSV vaccine is recommended only September through January. Those who provide health care to pregnant patients who live in areas with different patterns of RSV seasonality, such as Alaska, Hawaii, parts of Florida, or other jurisdictions outside the continental United States, should follow guidance from state or territorial public health authorities about the timing of RSV vaccination during pregnancy in their regions.<br />
              RSV vaccine is only recommended as a single dose; revaccination is not recommended. However, RSV vaccination during one pregnancy is not expected to protect infants resulting from future pregnancies. Therefore, a patient who is currently pregnant and received RSV vaccine before the current pregnancy should be counseled that their infant should be immunized with an RSV preventive antibody for protection against RSV disease after birth.</p>

              <h3 style={{textAlign:'left', fontSize:'1.15rem', fontWeight:700, color:'#40606D', direction: 'ltr'}}>Should RSV vaccine be given during every pregnancy?</h3>
              <p className="about-lang-intro" style={{direction: 'ltr', textAlign: 'left'}}>No. RSV vaccination during pregnancy is only recommended for pregnant people who have not previously received an RSV vaccine and who are at the recommended stage of pregnancy (32 weeks through 36 weeks 6 days' gestation) during the recommended time of year (typically September through January).</p>

              <h3 style={{textAlign:'left', fontSize:'1.15rem', fontWeight:700, color:'#40606D', direction: 'ltr'}}>Can I give RSV vaccine to someone who is at 36 weeks and 5 days' gestation?</h3>
              <p className="about-lang-intro" style={{direction: 'ltr', textAlign: 'left'}}>Yes. Pfizer's RSV vaccine (Abrysvo) may be administered to a previously unvaccinated pregnant person from 32 weeks through 36 weeks and 6 days' gestation. RSV vaccine should not be administered to someone at 37 weeks' gestation or beyond.<br />
              RSV vaccine should be administered at least 2 weeks before delivery to allow time for the maternal immune system to create antibodies and transfer sufficient antibodies to the fetus for adequate protection after birth. If the gestational age is appropriate, but clinical judgment is that delivery is likely to occur within 2 weeks, it is reasonable to defer vaccination and plan to immunize the infant with an RSV preventive antibody product after delivery. Infants born less than 14 days after maternal RSV vaccination are recommended to be immunized with an RSV preventive antibody product after birth to ensure adequate protection.</p>

              <h3 style={{textAlign:'left', fontSize:'1.15rem', fontWeight:700, color:'#40606D', direction: 'ltr'}}>Do pregnant people have a choice about whether to receive Abrysvo during pregnancy or to immunize their infant with an RSV preventive antibody product?</h3>
              <p className="about-lang-intro" style={{direction: 'ltr', textAlign: 'left'}}>Many pregnant people will have a choice about whether to get Abrysvo during pregnancy or to immunize their infant with an RSV preventive antibody product after birth. Those who are previously unvaccinated and between 32 and 36 weeks 6 days' gestation between September and January, may be vaccinated with Abrysvo or have their infant receive an RSV preventive antibody product soon after birth (preferably within the first week of life if born during a month when RSV preventive antibody product administration is recommended).<br />
              It is important to note that both Abrysvo RSV vaccine and RSV preventive antibody products may not be available or an option for all people in all settings. In some facilities or circumstances, only one option might be available: those offered Abrysvo during pregnancy may not wish to defer that option unless they are confident that an RSV preventive antibody product will be available for their infant. Conversely, if the pregnant person received RSV vaccine before the current pregnancy, only an RSV preventive antibody product administered after birth is recommended for RSV prevention. All infants up to 8 months 0 days of age whose mothers were not vaccinated may be given an RSV preventive antibody product when feasible, before or during their first RSV season.</p>

              <h3 style={{textAlign:'left', fontSize:'1.15rem', fontWeight:700, color:'#40606D', direction: 'ltr'}}>By what route should RSV vaccine be given?</h3>
              <p className="about-lang-intro" style={{direction: 'ltr', textAlign: 'left'}}>All three RSV vaccines (Arexvy, Abrysvo, mResvia) are administered by the intramuscular route.</p>

              <h3 style={{textAlign:'left', fontSize:'1.15rem', fontWeight:700, color:'#40606D', direction: 'ltr'}}>Can RSV vaccine be administered at the same time as other vaccines?</h3>
              <p className="about-lang-intro" style={{direction: 'ltr', textAlign: 'left'}}>Yes. It is acceptable to administer any of the three available RSV vaccines at the same time as other recommended vaccines, in accordance with CDC's general best practice guidelines for immunization. This is especially important if you are concerned an unvaccinated patient will not return or if the patient's immediate risk is high (such as when seasonal influenza, RSV, and COVID-19 are circulating).</p>
              <p className="about-lang-intro" style={{direction: 'ltr', textAlign: 'left'}}>Coadministration might increase short-term side effects (greater reactogenicity), such as fever, soreness, body aches, or headache, especially when administering more than one vaccine containing a non-aluminum adjuvant designed to enhance the immune response. While these side effects are not unsafe, they may be unpleasant for a day or two. If you are confident that a patient will return, the patient may prefer to separate the administration of vaccines that are less time-sensitive (e.g., shingles vaccine) to reduce the likelihood of uncomfortable side effects. There is no specific minimum interval between non-live vaccines, so separation by just a few days is acceptable, if desired.</p>

              <h3 style={{textAlign:'left', fontSize:'1.15rem', fontWeight:700, color:'#40606D', direction: 'ltr'}}>An error was made resulting in an infant receiving RSV vaccine instead of the nirsevimab RSV preventive antibody. What should be done?</h3>
              <p className="about-lang-intro" style={{direction: 'ltr', textAlign: 'left'}}>The safety and effectiveness of RSV vaccines have not been studied in infants. The family should be informed of the error, and an RSV preventive antibody product, either nirsevimab (Beyfortus, Sanofi) or clesrovimab (Enflonsia, Merck), should be administered as recommended as soon as feasible. CDC experts recommend that if you administer the preventive antibody product within 72 hours of the error, and you know where the RSV vaccine was injected, you should administer the preventive antibody product in a different anatomic site. Facilities that stock RSV vaccine and RSV preventive antibody products should put systems and procedures in place to prevent this type of error, including staff training, clear labeling, and warnings in storage units.</p>

              <h3 style={{textAlign:'left', fontSize:'1.15rem', fontWeight:700, color:'#40606D', direction: 'ltr'}}>How is an RSV preventive antibody product different from a vaccine?</h3>
              <p className="about-lang-intro" style={{direction: 'ltr', textAlign: 'left'}}>Vaccination involves active immunization, where an antigen is administered to a recipient to activate the recipient's immune system and generate an immune response (which includes developing antibodies). Active immunization may require up to 2 weeks to have its full protective effect, and sometimes a series of vaccinations is required. Protection may last for months or be life-long, depending upon the type of immune response triggered. The effectiveness of a vaccine depends on the recipient's immune system.</p>
              <p className="about-lang-intro" style={{direction: 'ltr', textAlign: 'left'}}>Nirsevimab (Beyfortus, Sanofi) and clesrovimab (Enflonsia, Merck) are injectable, long-acting monoclonal antibody products that gives the recipient direct, immediate protection through passive immunization. The antibodies circulate in the bloodstream and recognize and attach to the RSV virus if encountered, leading to elimination of the virus. These antibodies protect the patient for at least 5 months until they gradually break down and disappear. The highest risk of severe RSV infection and hospitalization for children is during their first RSV season as an infant. RSV preventive antibody products will not prevent children from getting RSV infections in future seasons, but the general risk of hospitalization due to RSV in childhood is far lower after infancy.</p>

              <h3 style={{textAlign:'left', fontSize:'1.15rem', fontWeight:700, color:'#40606D', direction: 'ltr'}}>How long does protection from RSV preventive antibody products last?</h3>
              <p className="about-lang-intro" style={{direction: 'ltr', textAlign: 'left'}}>The nirsevimab (Beyfortus, Sanofi) and clesrovimab (Enflonsia, Merck) clinical trials demonstrated effective protection lasted at least 5 months (150 days) in preventing severe RSV disease (disease requiring medical attention or hospitalization). Protection may persist longer than 5 months, but this was the period of time studied in the trials.</p>

              <h3 style={{textAlign:'left', fontSize:'1.15rem', fontWeight:700, color:'#40606D', direction: 'ltr'}}>Is palivizumab (Synagis, AstraZeneca) recommended for any infant?</h3>
              <p className="about-lang-intro" style={{direction: 'ltr', textAlign: 'left'}}>Palivizumab (Synagis) is a short-acting monoclonal antibody for the prevention of RSV disease in certain high-risk infants. It is given as a series of 5 monthly injections during an RSV season. With the availability of two long-acting preventive antibody products, clesrovimab and nirsevimab, each requiring only one dose for an entire RSV season, the American Academy of Pediatrics no longer recommends Synagis. The manufacturer has announced that the product is to be discontinued in December 2025.</p>

              <h3 style={{textAlign:'left', fontSize:'1.15rem', fontWeight:700, color:'#40606D', direction: 'ltr'}}>What time of year is an RSV preventive antibody product recommended to be given to infants and toddlers?</h3>
              <p className="about-lang-intro" style={{direction: 'ltr', textAlign: 'left'}}>The optimal timing for nirsevimab (Beyfortus, Sanofi) or clesrovimab (Enflonsia, Merck) to be administered is shortly before the RSV season begins; however, these products may be administered to eligible infants and children at any time during the season.</p>
              <p className="about-lang-intro" style={{direction: 'ltr', textAlign: 'left'}}>The time to administer RSV preventive antibody products is during the months of October through March in most areas in the United States, unless otherwise advised by state or territorial public health authorities. Adjustment of timing due to RSV activity outside this typical timeframe is most likely to be necessary in tropical or sub-tropical climates and in Alaska.</p>

              <h3 style={{textAlign:'left', fontSize:'1.15rem', fontWeight:700, color:'#40606D', direction: 'ltr'}}>When should palivizumab (Synagis) be used now that nirsevimab and clesrovimab are recommended?</h3>
              <p className="about-lang-intro" style={{direction: 'ltr', textAlign: 'left'}}>Palivizumab (Synagis, AstraZeneca) is a short-acting monoclonal antibody product that is administered monthly. Synagis is no longer recommended for use by the American Academy of Pediatrics (AAP). The manufacturer is discontinuing the product in December 2025.</p>

              <h3 style={{textAlign:'left', fontSize:'1.15rem', fontWeight:700, color:'#40606D', direction: 'ltr'}}>A 2-week-old infant whose mother had limited prenatal care is a new patient. The mother might have had RSV vaccine, but we can't be sure. What do we do?</h3>
              <p className="about-lang-intro" style={{direction: 'ltr', textAlign: 'left'}}>If you are unable to obtain prenatal records or verify receipt of maternal RSV vaccine, CDC recommends that the baby receive nirsevimab (Beyfortus, Sanofi) or clesrovimab (Enflonsia, Merck), particularly if it is shortly before or during the RSV season. Don't forget to check the state immunization information system (IIS) for the mother's vaccination record. RSV vaccination during a previous pregnancy does not protect through later pregnancies. If the mother received RSV vaccine during a previous pregnancy, nirsevimab or clesrovimab is indicated for this infant. It is also important to attempt to verify from the birthing facility records whether this baby received an RSV preventive antibody product prior to discharge to avoid giving an unnecessary second dose.</p>

              <h3 style={{textAlign:'left', fontSize:'1.15rem', fontWeight:700, color:'#40606D', direction: 'ltr'}}>My patient's mother was vaccinated for RSV at 33 weeks' gestation but delivered the baby a week later. It is now January. Does this infant need an RSV preventive antibody product?</h3>
              <p className="about-lang-intro" style={{direction: 'ltr', textAlign: 'left'}}>Yes. Infants born less than 14 days after the mother received RSV vaccine should receive nirsevimab (Beyfortus, Sanofi) or clesrovimab (Enflonsia, Merck). Infants born within 14 days after maternal vaccination may not have had sufficient time in utero to receive adequate protection from maternal RSV antibodies produced after vaccination. Infants born 14 days or more after maternal vaccination are not recommended to receive an RSV preventive antibody product except in rare circumstances where maternal antibodies may be insufficiently effective.</p>

              <h3 style={{textAlign:'left', fontSize:'1.15rem', fontWeight:700, color:'#40606D', direction: 'ltr'}}>When might an infant entering the first RSV season need an RSV preventive antibody product even though the mother was properly vaccinated more than 14 days before delivery?</h3>
              <p className="about-lang-intro" style={{direction: 'ltr', textAlign: 'left'}}>In rare circumstances, nirsevimab (Beyfortus, Sanofi) or clesrovimab (Enflonsia, Merck) may be considered for infants in their first RSV season who were born to RSV-vaccinated mothers. These situations may include:<br />
              infants born to mothers who have health conditions that might prevent an adequate maternal immune response to vaccination (an immunocompromising condition caused by disease or immunosuppressive treatment)<br />
              infants whose mothers have conditions associated with reduced transplacental antibody transfer (such as a mother living with HIV infection)<br />
              infants who might have lost maternal antibodies, such as those who have undergone cardiopulmonary bypass or extracorporeal membrane oxygenation (ECMO)<br />
              infants with substantially increased risk for severe RSV disease (such as hemodynamically significant congenital heart disease or intensive care admission requiring oxygen at hospital discharge)<br />
              Infants and children age 8 through 19 months who are at increased risk for severe RSV disease and are entering their second RSV season are recommended to receive nirsevimab (Beyfortus) regardless of history of maternal vaccination. Clesrovimab is not recommended for children age 8 months or older.</p>

              <h3 style={{textAlign:'left', fontSize:'1.15rem', fontWeight:700, color:'#40606D', direction: 'ltr'}}>Should we give an RSV preventive antibody product to an infant who is younger than 8 months of age in October but whose mother received Abrysvo RSV vaccine during pregnancy with this infant last winter?</h3>
              <p className="about-lang-intro" style={{direction: 'ltr', textAlign: 'left'}}>ACIP routinely recommends nirsevimab (Beyfortus, Sanofi) or clesrovimab (Enflonsia, Merck) only for infants younger than 8 months of age whose mothers were not vaccinated, or not effectively vaccinated, with Abrysvo (Pfizer) RSV vaccine during their pregnancy. RSV preventive antibody products are not recommended for this infant unless there is a clinical reason to believe maternal vaccination was ineffective, for example, if the infant had been born less than 14 days after vaccine administration.</p>

              <h3 style={{textAlign:'left', fontSize:'1.15rem', fontWeight:700, color:'#40606D', direction: 'ltr'}}>Can an RSV preventive antibody product be coadministered with vaccines?</h3>
              <p className="about-lang-intro" style={{direction: 'ltr', textAlign: 'left'}}>Yes, nirsevimab (Beyfortus, Sanofi) or clesrovimab (Enflonsia, Merck) may be coadministered with all other recommended age-appropriate vaccines. An RSV preventive antibody product should not interfere with the immune response to routine childhood vaccines when given together or at any time before or after them. Likewise, vaccination does not interfere with the effectiveness of the preventive antibody product.</p>
              <p className="about-lang-intro" style={{direction: 'ltr', textAlign: 'left'}}>When giving several injections at a single visit, separate intramuscular vaccines by at least 1 inch in the body of the muscle, if possible, to reduce the likelihood of overlapping local injection site reactions.</p>

              <h3 style={{textAlign:'left', fontSize:'1.15rem', fontWeight:700, color:'#40606D', direction: 'ltr'}}>Does administration of hepatitis B immune globulin (HBIG) at birth affect the recommended timing of an RSV preventive antibody product?</h3>
              <p className="about-lang-intro" style={{direction: 'ltr', textAlign: 'left'}}>No, these two antibody preparations should not interfere with each other. Administer nirsevimab (Beyfortus, Sanofi) or clesrovimab (Enflonsia, Merck) as recommended.</p>

              <h3 style={{textAlign:'left', fontSize:'1.15rem', fontWeight:700, color:'#40606D', direction: 'ltr'}}>When is the optimal timing for infants and toddlers to receive an RSV preventive antibody product?</h3>
              <p className="about-lang-intro" style={{direction: 'ltr', textAlign: 'left'}}>Aim for nirsevimab (Beyfortus, Sanofi) or clesrovimab (Enflonsia, Merck) administration in the first week of life for infants born shortly before or during the RSV season (typically October through March, unless directed otherwise by state or territorial public health officials). Ideally, eligible infants should be immunized before discharge from the birthing facility. Eligible infants with prolonged birth hospitalizations due to prematurity or other causes should be immunized shortly before or promptly after discharge.<br />
              Infants younger than age 8 months born outside of the RSV season, as well as older children at high risk who are recommended be protected in their second RSV season, should aim to be immunized shortly before the start of the RSV season (typically October).<br />
              If the ideal timing is missed, age-eligible infants and children who have not yet received a dose may be immunized at any time during the RSV season.</p>

              <h3 style={{textAlign:'left', fontSize:'1.15rem', fontWeight:700, color:'#40606D', direction: 'ltr'}}>What are the common side effects of the RSV vaccines?</h3>
              <p className="about-lang-intro" style={{direction: 'ltr', textAlign: 'left'}}>In clinical trials of the three licensed and recommended RSV vaccines, Arexvy (GSK), Pfizer (Abrysvo), and mResvia (Moderna), mild, local injection site reactions (redness, swelling), fatigue, muscle aches, and headache were common.</p>

              <h3 style={{textAlign:'left', fontSize:'1.15rem', fontWeight:700, color:'#40606D', direction: 'ltr'}}>Is there a risk of Guillain-Barré syndrome (GBS) and related conditions with RSV vaccine?</h3>
              <p className="about-lang-intro" style={{direction: 'ltr', textAlign: 'left'}}>In the clinical trials of both RSVPreF3 (Arexvy, GSK) and RSVpreF (Abrysvo, Pfizer) vaccines, a small number of inflammatory neurologic events, including GBS, were reported after RSV vaccination. Further FDA studies presented to the ACIP in October 2024 suggest a small increased risk of GBS of a similar magnitude for both products, approximately 7-9 excess cases per 1 million doses given. No cases of GBS or other inflammatory neurologic events were reported after mRNA RSV (mResvia) vaccination during the clinical trials. CDC and FDA continue to actively monitor the safety of all of these vaccines through national safety surveillance systems.<br />
              Estimates presented to ACIP in October 2024 comparing the benefit of RSV vaccination in the older adult population for whom it is recommended to the small increased risk of GBS following Arexvy or Abrysvo show that vaccination of a million people would prevent thousands more hospitalizations and hundreds more deaths than the small number of GBS cases vaccination may trigger. Because the benefits of preventing RSV in the recommended population far outweigh the potential risk of GBS, no changes to recommendations have been made.</p>

              <h3 style={{textAlign:'left', fontSize:'1.15rem', fontWeight:700, color:'#40606D', direction: 'ltr'}}>What are the side effects of RSV preventive antibody products?</h3>
              <p className="about-lang-intro" style={{direction: 'ltr', textAlign: 'left'}}>In clinical trials, the vast majority of infants had no side effects detected after nirsevimab (Beyfortus, Sanofi) or clesrovimab (Enflonsia, Merck) administration. For both products, the proportion of infants experiencing side effects was very similar in the intervention and placebo groups.<br />
              The most common side effects noted during the clinical trials of nirsevimab were rash occurring within 2 weeks after injection (seen in 0.9% of nirsevimab recipients versus 0.6% of placebo recipients) and injection site reactions (including redness, pain, swelling) occurring within 7 days after injection (0.3% of nirsevimab recipients versus 0% of placebo recipients).<br />
              Similar reactions were seen with clesrovimab. Rash was seen within two weeks after injection (2.3% of clesrovimab recipients vs. 1.9% of placebo recipients). Redness or swelling at the injection site each were reported in fewer than 4% of clesrovimab recipients, with a similar proportion of placebo recipients also reporting these side effects. See the product package inserts for more details.</p>

              <h3 style={{textAlign:'left', fontSize:'1.15rem', fontWeight:700, color:'#40606D', direction: 'ltr'}}>My family practice office has both RSV vaccine and nirsevimab (Beyfortus) left over at the end of RSV season. Should we discard them after the end of the season, as we do influenza vaccines?</h3>
              <p className="about-lang-intro" style={{direction: 'ltr', textAlign: 'left'}}>No. Seasonal influenza vaccines are reformulated each year; for this reason, all unused seasonal influenza vaccines expire and should be discarded no later than the end of June each season. RSV products (vaccines and preventive antibody) do not change each season and products in your storage unit now may not expire until sometime during or after the next season.<br />
              Unless state or territorial public health authorities advise otherwise based upon local conditions, RSV vaccine should not be given during pregnancy after January. Likewise, nirsevimab (Beyfortus, Sanofi) or clesrovimab (Enflonsia, Merck) should not be given to infants after March or before October unless specifically instructed by public health authorities because of differences in local RSV circulation patterns.<br />
              Vaccination of eligible adults age 50 years or older will have the most benefit if RSV vaccine is administered in late summer or early fall, just before the typical RSV season. However, eligible adults may be vaccinated at any time of year if there is a need to vaccinate at other times of year. Vaccination is expected to provide meaningful protection from serious RSV disease for 2 years or longer. Only one dose of RSV vaccine is recommended at this time: revaccination is not recommended but will be considered in the future.</p>
            </div>
          </div>
        </div>
      </section>
      <footer className="footer">
        <div className="footer-top">
          <div className="footer-content">
            <div className="footer-section">
              <h3 className="footer-title">Contact</h3>
              <p className="footer-text">I'm always looking for new and exciting opportunities. Let's connect.</p>
              <div className="footer-social">
                <a href="https://www.facebook.com/profile.php?id=100064747760120" className="social-link" aria-label="Facebook" target="_blank" rel="noopener noreferrer"><svg width="24" height="24" viewBox="0 0 24 24" fill="currentColor"><path d="M24 12.073c0-6.627-5.373-12-12-12s-12 5.373-12 12c0 5.99 4.388 10.954 10.125 11.854v-8.385H7.078v-3.47h3.047V9.43c0-3.007 1.792-4.669 4.533-4.669 1.312 0 2.686.235 2.686.235v2.953H15.83c-1.491 0-1.956.925-1.956 1.874v2.25h3.328l-.532 3.47h-2.796v8.385C19.612 23.027 24 18.062 24 12.073z"/></svg></a>
                <a href="https://www.instagram.com/talkvaccine?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw%3D%3D" className="social-link" aria-label="Instagram" target="_blank" rel="noopener noreferrer"><svg width="24" height="24" viewBox="0 0 24 24" fill="currentColor"><path d="M12 2.163c3.204 0 3.584.012 4.85.07 3.252.148 4.771 1.691 4.919 4.919.058 1.265.069 1.645.069 4.849 0 3.205-.012 3.584-.069 4.849-.149 3.225-1.664 4.771-4.919 4.919-1.266.058-1.644.07-4.85.07-3.204 0-3.584-.012-4.849-.07-3.26-.149-4.771-1.699-4.919-4.92-.058-1.265-.07-1.644-.07-4.849 0-3.204.013-3.583.07-4.849.149-3.227 1.664-4.771 4.919-4.919 1.266-.057 1.645-.069 4.849-.069zm0-2.163c-3.259 0-3.667.014-4.947.072-4.358.2-6.78 2.618-6.98 6.98-.059 1.281-.073 1.689-.073 4.948 0 3.259.014 3.668.072 4.948.2 4.358 2.618 6.78 6.98 6.98 1.281.058 1.689.072 4.948.072 3.259 0 3.668-.014 4.948-.072 4.354-.2 6.782-2.618 6.979-6.98.059-1.28.073-1.689.073-4.948 0-3.259-.014-3.667-.072-4.947-.196-4.354-2.617-6.78-6.979-6.98-1.281-.059-1.69-.073-4.949-.073zm0 5.838c-3.403 0-6.162 2.759-6.162 6.162s2.759 6.163 6.162 6.163 6.162-2.759 6.162-6.163c0-3.403-2.759-6.162-6.162-6.162zm0 10.162c-2.209 0-4-1.79-4-4 0-2.209 1.791-4 4-4s4 1.791 4 4c0 2.21-1.791 4-4 4zm6.406-11.845c-.796 0-1.441.645-1.441 1.44s.645 1.44 1.441 1.44c.795 0 1.439-.645 1.439-1.44s-.644-1.44-1.439-1.44z"/></svg></a>
                <a href="https://www.youtube.com/@VaccineTalk" className="social-link" aria-label="YouTube" target="_blank" rel="noopener noreferrer"><svg width="24" height="24" viewBox="0 0 24 24" fill="currentColor"><path d="M23.498 6.186a3.016 3.016 0 0 0-2.122-2.136C19.505 3.545 12 3.545 12 3.545s-7.505 0-9.377.505A3.017 3.017 0 0 0 .502 6.186C0 8.07 0 12 0 12s0 3.93.502 5.814a3.016 3.016 0 0 0 2.122 2.136c1.871.505 9.376.505 9.376.505s7.505 0 9.377-.505a3.015 3.015 0 0 0 2.122-2.136C24 15.93 24 12 24 12s0-3.93-.502-5.814zM9.545 15.568V8.432L15.818 12l-6.273 3.568z"/></svg></a>
              </div>
            </div>
            <div className="footer-section"><a href="/disclaimer" className="disclaimer-btn" style={{textDecoration: "none", display: "inline-block"}}>Disclaimer</a></div>
          </div>
        </div>
        <div className="footer-bottom">
          <div className="footer-copyright"><p className="copyright-text">© 2025 Vaccine Talk – All rights reserved.</p><p className="copyright-text">Content is original and may not be copied without permission.</p></div>
          <div className="footer-policy"><a href="/copy" className="policy-link">Copyright & Content Policy</a><span className="separator">|</span><a href="/copy" className="policy-link arabic">حقوق النشر والاستخدام</a></div>
        </div>
      </footer>
    </div>
  );
}


